class Message:
    # A message is some content generated by an actor, the actor could be "user", "assistant" or some "tools"
    pass


class Dialogue:
    # A dialogue is a sequence of messages
    # In our case, the dialogue would be a message by the user "when is born XXX?"
    # followed by a message from the assistant, eventually followed by a tool's message before an assistant's conclusion
    pass


# TODO create Dialogue tokenizer, that produce tokens, as well as a mask of token on which we should train.
