log_path: $HOME/logs/eval.jsonl
db_path: apps/memory/dataset/people.db
data:
  source: apps/memory/dataset/qatool.jsonl
  batch_size: 16
  asynchronous: false
tmp_file: $HOME/logs/tmp_eval.jsonl
tokenizer:
  name: byte