log_path: $HOME/logs/eval.jsonl
db_path: data/memory/people.db
data:
  source: data/memory/qatool.jsonl
  batch_size: 16
  asynchronous: false
tmp_file: $HOME/logs/tmp_eval.jsonl
tokenizer:
  name: byte