launcher:
  torchrun: false
  name: memory
  overwrite: true
  log_dir: $HOME/memory_finetune

  script: apps.memory.finetune

  slurm:
    mem: 16G
    nodes: 1
    nb_gpus: 2        # use torchrun, or slurm, for multi-gpu runs
    time: 10          # job time in minutes
    signal_time: 60   # alert time in seconds

run_config:
  compile: false

  cluster:
    tp: 1

  data:
    batch_size: 128
    seq_len: 1024
    padding: true

    nb_data: 1000
    key: qatool
    data_dir: $HOME/data/memory
    save_dir: $HOME/data/temporary

  tokenizer:
    implementation: pretrained
    tokenizer_id: gpt2
    special_tokens:
      <|user|>: 0
      <|assistant|>: 1
      <|database|>: 2
      <|eod|>: 3

  model:
    model_id: gpt2

  optim:
    steps: 100
    lr: 1e-3
    weight_decay: 0.1
    fused: true
    warmup: 50
    lr_min_ratio: 0

  orchestration:
    utils:
      seed: 100

    logging:
      period: 10
      level: INFO

    profiler:
      pytorch:
        active: false
        wait: 1
        steps: 10
      light:
        period: 25

  evaluation:
    db_path: $HOME/data/memory/people.db
    period: 50
    asynchronous: false
    data:
      batch_size: 1024
    slurm:
      nb_gpus: 1