launcher:
  name: memory
  overwrite: true
  log_dir: $HOME/memory_grid

  script: apps.memory.train

  grid:
    data:
      n_data: [10, 30, 100, 300, 1000, 3000, 10000]
      key: [qatool, qa]
    model:
      emb_dim: [16, 32, 64, 128]
      nb_layers: [1, 2, 3, 4, 5, 6]
      block: 
        nb_heads: [1, 2, 4, 8]

  slurm:
    # partition: scavenge
    mem: 32G
    nodes: 1
    nb_gpus: 1         # use torchrun, or slurm, for multi-gpu runs
    time: 1440         # job time in minutes
    signal_time: 120   # alert time in seconds

run_config:
  cluster:
    compile_model: false

  data:
    key: qatool
    n_data: 100
    batch_size: 128
    seq_len: 256
    padding: true
    tokenizer:
      name: byte
      special_tokens:
        <|user|>: 0
        <|assistant|>: 1
        <|database|>: 2
        <|eod|>: 3

  model:
    implementation: transformer
    flex_attention: false
    vocab_size: 300
    emb_dim: 64
    nb_layers: 2
    block:
      nb_heads: 2

  optim:
    steps: 10000
    lr: 1e-3
    weight_decay: 0.1
    fused: true
    warmup: 50
    lr_min_ratio: 0

  orchestration:
    utils:
      seed: 100

    logging:
      period: 1
    wandb:
      active: false

    checkpoint:
      nb_kept: 1

    profiler:
      active: true
      heavy: false
      wait: 1
      steps: 20

  evaluation:
    period: 20
    asynchronous: false

    db_path: $HOME/data/memory/people.db