launcher:
  name: memory
  overwrite: true
  log_dir: $HOME/memory_ood_10


  slurm:
    # partition: scavenge
    mem: 32G
    nodes: 1
    nb_gpus: 1         # use torchrun, or slurm, for multi-gpu runs
    time: 1440         # job time in minutes
    signal_time: 120   # alert time in seconds

run_config:
  cluster:
    tp: 1
    device: 2

  data:
    key: qatool
    nb_data: 65_536
    batch_size: 128
    seq_len: 257
    padding: true
    seed: 0

  tokenizer:
    implementation: byte
    special_tokens:
      <|user|>: 0
      <|assistant|>: 1
      <|database|>: 2
      <|eod|>: 3

  model:
    implementation: transformer
    vocab_size: 260
    emb_dim: 40
    nb_layers: 2
    block:
      nb_heads: 2

  optim:
    steps: 100_000
    lr: 1e-3
    weight_decay: 0.1
    warmup: 50
    lr_min_ratio: 0

  orchestration:
    utils:
      seed: 100

    logging:
      period: 100
      wandb:
        active: false

    checkpoint:
      nb_kept: 1

  evaluation:
    period: 1_000
    asynchronous: false
    db_path: $HOME/ood_data/memory/people.db
    data:
      batch_size: 1024
